{
  "asyncapi": "3.0.0",
  "info": {
    "title": "shipping-service",
    "version": "0.0.1",
    "x-generator": "springwolf"
  },
  "defaultContentType": "application/json",
  "servers": {
    "kafka": {
      "host": "localhost:29092",
      "protocol": "kafka"
    }
  },
  "channels": {
    "ExternalTransferCompleted": {
      "address": "ExternalTransferCompleted",
      "messages": {
        "ExternalTransferCompleted": {
          "$ref": "#/components/messages/ExternalTransferCompleted"
        }
      }
    },
    "OrderFulfilled": {
      "address": "OrderFulfilled",
      "messages": {
        "OrderFulfilled": {
          "$ref": "#/components/messages/OrderFulfilled"
        }
      }
    },
    "ShipmentCompleted": {
      "address": "ShipmentCompleted",
      "messages": {
        "ShipmentCompleted": {
          "$ref": "#/components/messages/ShipmentCompleted"
        }
      }
    },
    "ShipmentCreated": {
      "address": "ShipmentCreated",
      "messages": {
        "ShipmentCreated": {
          "$ref": "#/components/messages/ShipmentCreated"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ExternalTransferCompleted": {
        "title": "ExternalTransferCompleted",
        "type": "object",
        "properties": {
          "eventId": {
            "title": "Event ID",
            "type": "string",
            "description": "The event ID",
            "format": "uuid",
            "examples": [
              "ae94cf69-6863-4c26-ad34-99347a9a4c8a"
            ]
          },
          "eventType": {
            "title": "Event Type",
            "type": "string",
            "description": "The event type",
            "examples": [
              "EventReceived"
            ]
          },
          "eventVersion": {
            "title": "Event Version",
            "type": "string",
            "description": "The event version",
            "examples": [
              "1.0"
            ]
          },
          "occurredOn": {
            "title": "Occurred On",
            "type": "string",
            "description": "When the event occurred",
            "format": "date-time",
            "examples": [
              "2024-10-07T20:59:16.925110827Z"
            ]
          },
          "payload": {
            "$ref": "#/components/schemas/ExternalTransferCompletedPayload"
          }
        },
        "description": "External Transfer Completed Event",
        "examples": [
          {
            "eventId": "ae94cf69-6863-4c26-ad34-99347a9a4c8a",
            "eventType": "EventReceived",
            "eventVersion": "1.0",
            "occurredOn": "2024-10-07T20:59:16.925110827Z",
            "payload": {
              "createDate": "2024-10-03T15:44:42.328889299Z",
              "createdByEmployeeId": "4c973896-5761-41fc-8217-07c5d13a004b",
              "customerCodeFrom": "ABC123",
              "customerCodeTo": "ABC123",
              "externalTransferItems": [
                {
                  "productCode": "string",
                  "unitNumber": "string"
                }
              ],
              "hospitalTransferId": "#XYZ56",
              "transferDate": "2024-12-31"
            }
          }
        ],
        "required": [
          "eventId",
          "eventType",
          "eventVersion",
          "occurredOn",
          "payload"
        ]
      },
      "ExternalTransferCompletedPayload": {
        "title": "ExternalTransferCompletedPayload",
        "type": "object",
        "properties": {
          "createDate": {
            "title": "Create date",
            "type": "string",
            "description": "The date order was created",
            "format": "date-time",
            "examples": [
              "2024-10-03T15:44:42.328889299Z"
            ]
          },
          "createdByEmployeeId": {
            "title": "Create Employee ID",
            "type": "string",
            "description": "The employee ID that created the record",
            "examples": [
              "4c973896-5761-41fc-8217-07c5d13a004b"
            ]
          },
          "customerCodeFrom": {
            "title": "customerCodeFrom",
            "type": "string",
            "description": "Customer Code From",
            "examples": [
              "ABC123"
            ]
          },
          "customerCodeTo": {
            "title": "customerCodeTo",
            "type": "string",
            "description": "Customer Code To",
            "examples": [
              "ABC123"
            ]
          },
          "externalTransferItems": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ExternalTransferOutputItem"
            }
          },
          "hospitalTransferId": {
            "title": "hospitalTransferId",
            "type": "string",
            "description": "Hospital Transfer Id",
            "examples": [
              "#XYZ56"
            ]
          },
          "transferDate": {
            "title": "transferDate",
            "type": "string",
            "description": "Transfer Date",
            "format": "date",
            "examples": [
              "2025-01-01T00:00:00.000+00:00"
            ]
          }
        },
        "description": "External Transfer Completed Event Payload",
        "examples": [
          {
            "createDate": "2024-10-03T15:44:42.328889299Z",
            "createdByEmployeeId": "4c973896-5761-41fc-8217-07c5d13a004b",
            "customerCodeFrom": "ABC123",
            "customerCodeTo": "ABC123",
            "externalTransferItems": [
              {
                "productCode": "string",
                "unitNumber": "string"
              }
            ],
            "hospitalTransferId": "#XYZ56",
            "transferDate": "2024-12-31"
          }
        ],
        "required": [
          "createDate",
          "createdByEmployeeId",
          "customerCodeFrom",
          "customerCodeTo",
          "transferDate"
        ]
      },
      "Headers-1862616811": {
        "title": "Headers-1862616811",
        "type": "object",
        "properties": {
          "__TypeId__": {
            "type": "string",
            "description": "Spring Type Id Header",
            "enum": [
              "com.arcone.biopro.distribution.order.infrastructure.event.ShipmentCompletedOutputEvent"
            ],
            "examples": [
              "com.arcone.biopro.distribution.order.infrastructure.event.ShipmentCompletedOutputEvent"
            ]
          }
        },
        "examples": [
          {
            "__TypeId__": "com.arcone.biopro.distribution.order.infrastructure.event.ShipmentCompletedOutputEvent"
          }
        ]
      },
      "Headers-512730896": {
        "title": "Headers-512730896",
        "type": "object",
        "properties": {
          "__TypeId__": {
            "type": "string",
            "description": "Spring Type Id Header",
            "enum": [
              "com.arcone.biopro.distribution.order.infrastructure.event.ShipmentCreatedOutputEvent"
            ],
            "examples": [
              "com.arcone.biopro.distribution.order.infrastructure.event.ShipmentCreatedOutputEvent"
            ]
          }
        },
        "examples": [
          {
            "__TypeId__": "com.arcone.biopro.distribution.order.infrastructure.event.ShipmentCreatedOutputEvent"
          }
        ]
      },
      "Headers-610806439": {
        "title": "Headers-610806439",
        "type": "object",
        "properties": {
          "__TypeId__": {
            "type": "string",
            "description": "Spring Type Id Header",
            "enum": [
              "com.arcone.biopro.distribution.order.infrastructure.event.ExternalTransferCompletedOutputEvent"
            ],
            "examples": [
              "com.arcone.biopro.distribution.order.infrastructure.event.ExternalTransferCompletedOutputEvent"
            ]
          }
        },
        "examples": [
          {
            "__TypeId__": "com.arcone.biopro.distribution.order.infrastructure.event.ExternalTransferCompletedOutputEvent"
          }
        ]
      },
      "HeadersNotDocumented": {
        "title": "HeadersNotDocumented",
        "type": "object",
        "properties": {},
        "description": "There can be headers, but they are not explicitly documented.",
        "examples": [
          {}
        ]
      },
      "OrderFulfilled": {
        "title": "OrderFulfilled",
        "type": "object",
        "properties": {
          "eventId": {
            "type": "string",
            "format": "uuid"
          },
          "eventType": {
            "type": "string"
          },
          "eventVersion": {
            "type": "string"
          },
          "occurredOn": {
            "type": "string",
            "format": "date-time"
          },
          "payload": {
            "$ref": "#/components/schemas/OrderFulfilledPayload"
          }
        },
        "description": "Order Fulfilled Event",
        "examples": [
          {
            "eventId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "eventType": "string",
            "eventVersion": "string",
            "occurredOn": "2015-07-20T15:49:04-07:00",
            "payload": {
              "billingCustomerCode": "string",
              "billingCustomerName": "string",
              "comments": "string",
              "customerAddressAddressLine1": "string",
              "customerAddressAddressLine2": "string",
              "customerAddressCity": "string",
              "customerAddressCountry": "string",
              "customerAddressCountryCode": "string",
              "customerAddressDistrict": "string",
              "customerAddressPostalCode": "string",
              "customerAddressState": "string",
              "customerPhoneNumber": "string",
              "deliveryType": "string",
              "departmentName": "string",
              "externalId": "string",
              "id": 0,
              "items": [
                {
                  "bloodType": "string",
                  "comments": "string",
                  "id": 0,
                  "orderId": 0,
                  "productFamily": "string",
                  "quantity": 0,
                  "shortDateProducts": [
                    {
                      "productCode": "string",
                      "storageLocation": "string",
                      "unitNumber": "string"
                    }
                  ],
                  "totalAvailable": 0
                }
              ],
              "locationCode": "string",
              "orderNumber": 0,
              "priority": "string",
              "productCategory": "string",
              "shippingCustomerCode": "string",
              "shippingCustomerName": "string",
              "shippingDate": "2015-07-20",
              "shippingMethod": "string",
              "status": "string"
            }
          }
        ]
      },
      "OrderFulfilledPayload": {
        "title": "OrderFulfilledPayload",
        "type": "object",
        "properties": {
          "billingCustomerCode": {
            "type": "string"
          },
          "billingCustomerName": {
            "type": "string"
          },
          "comments": {
            "type": "string"
          },
          "customerAddressAddressLine1": {
            "type": "string"
          },
          "customerAddressAddressLine2": {
            "type": "string"
          },
          "customerAddressCity": {
            "type": "string"
          },
          "customerAddressCountry": {
            "type": "string"
          },
          "customerAddressCountryCode": {
            "type": "string"
          },
          "customerAddressDistrict": {
            "type": "string"
          },
          "customerAddressPostalCode": {
            "type": "string"
          },
          "customerAddressState": {
            "type": "string"
          },
          "customerPhoneNumber": {
            "type": "string"
          },
          "deliveryType": {
            "type": "string"
          },
          "departmentName": {
            "type": "string"
          },
          "externalId": {
            "type": "string"
          },
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.OrderItemFulfilledMessage"
            }
          },
          "locationCode": {
            "type": "string"
          },
          "orderNumber": {
            "type": "integer",
            "format": "int64"
          },
          "priority": {
            "type": "string"
          },
          "productCategory": {
            "type": "string"
          },
          "shippingCustomerCode": {
            "type": "string"
          },
          "shippingCustomerName": {
            "type": "string"
          },
          "shippingDate": {
            "type": "string",
            "format": "date"
          },
          "shippingMethod": {
            "type": "string"
          },
          "status": {
            "type": "string"
          }
        },
        "description": "Order Fulfilled Event Payload",
        "examples": [
          {
            "billingCustomerCode": "string",
            "billingCustomerName": "string",
            "comments": "string",
            "customerAddressAddressLine1": "string",
            "customerAddressAddressLine2": "string",
            "customerAddressCity": "string",
            "customerAddressCountry": "string",
            "customerAddressCountryCode": "string",
            "customerAddressDistrict": "string",
            "customerAddressPostalCode": "string",
            "customerAddressState": "string",
            "customerPhoneNumber": "string",
            "deliveryType": "string",
            "departmentName": "string",
            "externalId": "string",
            "id": 0,
            "items": [
              {
                "bloodType": "string",
                "comments": "string",
                "id": 0,
                "orderId": 0,
                "productFamily": "string",
                "quantity": 0,
                "shortDateProducts": [
                  {
                    "productCode": "string",
                    "storageLocation": "string",
                    "unitNumber": "string"
                  }
                ],
                "totalAvailable": 0
              }
            ],
            "locationCode": "string",
            "orderNumber": 0,
            "priority": "string",
            "productCategory": "string",
            "shippingCustomerCode": "string",
            "shippingCustomerName": "string",
            "shippingDate": "2015-07-20",
            "shippingMethod": "string",
            "status": "string"
          }
        ]
      },
      "ShipmentCompleted": {
        "title": "ShipmentCompleted",
        "type": "object",
        "properties": {
          "eventId": {
            "title": "Event ID",
            "type": "string",
            "description": "The event ID",
            "format": "uuid",
            "examples": [
              "ae94cf69-6863-4c26-ad34-99347a9a4c8a"
            ]
          },
          "eventType": {
            "title": "Event Type",
            "type": "string",
            "description": "The event type",
            "examples": [
              "EventReceived"
            ]
          },
          "eventVersion": {
            "title": "Event Version",
            "type": "string",
            "description": "The event version",
            "examples": [
              "1.0"
            ]
          },
          "occurredOn": {
            "title": "Occurred On",
            "type": "string",
            "description": "When the event occurred",
            "format": "date-time",
            "examples": [
              "2024-10-07T20:59:16.925110827Z"
            ]
          },
          "payload": {
            "$ref": "#/components/schemas/com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCompletedPayload"
          }
        },
        "description": "Shipment Completed Event",
        "examples": [
          {
            "eventId": "ae94cf69-6863-4c26-ad34-99347a9a4c8a",
            "eventType": "EventReceived",
            "eventVersion": "1.0",
            "occurredOn": "2024-10-07T20:59:16.925110827Z",
            "payload": {
              "createDate": "2015-07-20T15:49:04-07:00",
              "customerCode": "string",
              "customerType": "string",
              "externalOrderId": "string",
              "lineItems": [
                {
                  "bloodType": "string",
                  "productFamily": "string",
                  "products": [
                    {
                      "aboRh": "string",
                      "attributes": {
                        "key": "string"
                      },
                      "collectionDate": "2015-07-20T15:49:04-07:00",
                      "createDate": "2015-07-20T15:49:04-07:00",
                      "expirationDate": "2015-07-20T15:49:04-07:00",
                      "productCode": "string",
                      "productFamily": "string",
                      "unitNumber": "string"
                    }
                  ],
                  "quantity": 0
                }
              ],
              "locationCode": "string",
              "locationName": "string",
              "orderNumber": 0,
              "performedBy": "string",
              "services": [
                {
                  "code": "string",
                  "quantity": 0
                }
              ],
              "shipmentId": 0
            }
          }
        ],
        "required": [
          "eventId",
          "eventType",
          "eventVersion",
          "occurredOn",
          "payload"
        ]
      },
      "ShipmentCreated": {
        "title": "ShipmentCreated",
        "type": "object",
        "properties": {
          "eventId": {
            "title": "Event ID",
            "type": "string",
            "description": "The event ID",
            "format": "uuid",
            "examples": [
              "ae94cf69-6863-4c26-ad34-99347a9a4c8a"
            ]
          },
          "eventType": {
            "title": "Event Type",
            "type": "string",
            "description": "The event type",
            "examples": [
              "EventReceived"
            ]
          },
          "eventVersion": {
            "title": "Event Version",
            "type": "string",
            "description": "The event version",
            "examples": [
              "1.0"
            ]
          },
          "occurredOn": {
            "title": "Occurred On",
            "type": "string",
            "description": "When the event occurred",
            "format": "date-time",
            "examples": [
              "2024-10-07T20:59:16.925110827Z"
            ]
          },
          "payload": {
            "$ref": "#/components/schemas/com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCreatedPayloadDTO"
          }
        },
        "description": "Shipment Created Event",
        "examples": [
          {
            "eventId": "ae94cf69-6863-4c26-ad34-99347a9a4c8a",
            "eventType": "EventReceived",
            "eventVersion": "1.0",
            "occurredOn": "2024-10-07T20:59:16.925110827Z",
            "payload": {
              "orderNumber": 0,
              "shipmentId": 0,
              "shipmentStatus": "string"
            }
          }
        ],
        "required": [
          "eventId",
          "eventType",
          "eventVersion",
          "occurredOn",
          "payload"
        ]
      },
      "com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ExternalTransferOutputItem": {
        "title": "ExternalTransferOutputItem",
        "type": "object",
        "properties": {
          "productCode": {
            "type": "string"
          },
          "unitNumber": {
            "type": "string"
          }
        },
        "examples": [
          {
            "productCode": "string",
            "unitNumber": "string"
          }
        ]
      },
      "com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.OrderItemFulfilledMessage": {
        "title": "OrderItemFulfilledMessage",
        "type": "object",
        "properties": {
          "bloodType": {
            "type": "string"
          },
          "comments": {
            "type": "string"
          },
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "orderId": {
            "type": "integer",
            "format": "int64"
          },
          "productFamily": {
            "type": "string"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "shortDateProducts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShortDateItem"
            }
          },
          "totalAvailable": {
            "type": "integer",
            "format": "int32"
          }
        },
        "examples": [
          {
            "bloodType": "string",
            "comments": "string",
            "id": 0,
            "orderId": 0,
            "productFamily": "string",
            "quantity": 0,
            "shortDateProducts": [
              {
                "productCode": "string",
                "storageLocation": "string",
                "unitNumber": "string"
              }
            ],
            "totalAvailable": 0
          }
        ]
      },
      "com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCompletedItemPayload": {
        "title": "ShipmentCompletedItemPayload",
        "type": "object",
        "properties": {
          "bloodType": {
            "type": "string"
          },
          "productFamily": {
            "type": "string"
          },
          "products": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCompletedItemProductPayload"
            }
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          }
        },
        "examples": [
          {
            "bloodType": "string",
            "productFamily": "string",
            "products": [
              {
                "aboRh": "string",
                "attributes": {
                  "key": "string"
                },
                "collectionDate": "2015-07-20T15:49:04-07:00",
                "createDate": "2015-07-20T15:49:04-07:00",
                "expirationDate": "2015-07-20T15:49:04-07:00",
                "productCode": "string",
                "productFamily": "string",
                "unitNumber": "string"
              }
            ],
            "quantity": 0
          }
        ]
      },
      "com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCompletedItemProductPayload": {
        "title": "ShipmentCompletedItemProductPayload",
        "type": "object",
        "properties": {
          "aboRh": {
            "type": "string"
          },
          "attributes": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "collectionDate": {
            "type": "string",
            "format": "date-time"
          },
          "createDate": {
            "type": "string",
            "format": "date-time"
          },
          "expirationDate": {
            "type": "string",
            "format": "date-time"
          },
          "productCode": {
            "type": "string"
          },
          "productFamily": {
            "type": "string"
          },
          "unitNumber": {
            "type": "string"
          }
        },
        "examples": [
          {
            "aboRh": "string",
            "attributes": {
              "key": "string"
            },
            "collectionDate": "2015-07-20T15:49:04-07:00",
            "createDate": "2015-07-20T15:49:04-07:00",
            "expirationDate": "2015-07-20T15:49:04-07:00",
            "productCode": "string",
            "productFamily": "string",
            "unitNumber": "string"
          }
        ]
      },
      "com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCompletedPayload": {
        "title": "Payload",
        "type": "object",
        "properties": {
          "createDate": {
            "type": "string",
            "format": "date-time"
          },
          "customerCode": {
            "type": "string"
          },
          "customerType": {
            "type": "string"
          },
          "externalOrderId": {
            "type": "string"
          },
          "lineItems": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCompletedItemPayload"
            }
          },
          "locationCode": {
            "type": "string"
          },
          "locationName": {
            "type": "string"
          },
          "orderNumber": {
            "type": "integer",
            "format": "int64"
          },
          "performedBy": {
            "type": "string"
          },
          "services": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCompletedServicePayload"
            }
          },
          "shipmentId": {
            "type": "integer",
            "format": "int64"
          }
        },
        "description": "The event payload",
        "examples": [
          {
            "createDate": "2015-07-20T15:49:04-07:00",
            "customerCode": "string",
            "customerType": "string",
            "externalOrderId": "string",
            "lineItems": [
              {
                "bloodType": "string",
                "productFamily": "string",
                "products": [
                  {
                    "aboRh": "string",
                    "attributes": {
                      "key": "string"
                    },
                    "collectionDate": "2015-07-20T15:49:04-07:00",
                    "createDate": "2015-07-20T15:49:04-07:00",
                    "expirationDate": "2015-07-20T15:49:04-07:00",
                    "productCode": "string",
                    "productFamily": "string",
                    "unitNumber": "string"
                  }
                ],
                "quantity": 0
              }
            ],
            "locationCode": "string",
            "locationName": "string",
            "orderNumber": 0,
            "performedBy": "string",
            "services": [
              {
                "code": "string",
                "quantity": 0
              }
            ],
            "shipmentId": 0
          }
        ]
      },
      "com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCompletedServicePayload": {
        "title": "ShipmentCompletedServicePayload",
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          }
        },
        "examples": [
          {
            "code": "string",
            "quantity": 0
          }
        ]
      },
      "com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShipmentCreatedPayloadDTO": {
        "title": "Payload",
        "type": "object",
        "properties": {
          "orderNumber": {
            "type": "integer",
            "format": "int64"
          },
          "shipmentId": {
            "type": "integer",
            "format": "int64"
          },
          "shipmentStatus": {
            "type": "string"
          }
        },
        "description": "The event payload",
        "examples": [
          {
            "orderNumber": 0,
            "shipmentId": 0,
            "shipmentStatus": "string"
          }
        ]
      },
      "com.arcone.biopro.distribution.shipping.infrastructure.listener.dto.ShortDateItem": {
        "title": "ShortDateItem",
        "type": "object",
        "properties": {
          "productCode": {
            "type": "string"
          },
          "storageLocation": {
            "type": "string"
          },
          "unitNumber": {
            "type": "string"
          }
        },
        "examples": [
          {
            "productCode": "string",
            "storageLocation": "string",
            "unitNumber": "string"
          }
        ]
      }
    },
    "messages": {
      "ExternalTransferCompleted": {
        "headers": {
          "$ref": "#/components/schemas/Headers-610806439"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "$ref": "#/components/schemas/ExternalTransferCompleted"
          }
        },
        "name": "ExternalTransferCompleted",
        "title": "ExternalTransferCompleted",
        "description": "External Transfer Completed Event Payload",
        "bindings": {
          "kafka": {
            "bindingVersion": "0.5.0"
          }
        }
      },
      "OrderFulfilled": {
        "headers": {
          "$ref": "#/components/schemas/HeadersNotDocumented"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "$ref": "#/components/schemas/OrderFulfilled"
          }
        },
        "name": "OrderFulfilled",
        "title": "OrderFulfilled",
        "bindings": {
          "kafka": {
            "bindingVersion": "0.5.0"
          }
        }
      },
      "ShipmentCompleted": {
        "headers": {
          "$ref": "#/components/schemas/Headers-1862616811"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "$ref": "#/components/schemas/ShipmentCompleted"
          }
        },
        "name": "ShipmentCreated",
        "title": "ShipmentCreated",
        "description": "Shipment Created Event Payload",
        "bindings": {
          "kafka": {
            "bindingVersion": "0.5.0"
          }
        }
      },
      "ShipmentCreated": {
        "headers": {
          "$ref": "#/components/schemas/Headers-512730896"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "$ref": "#/components/schemas/ShipmentCreated"
          }
        },
        "name": "ShipmentCreated",
        "title": "ShipmentCreated",
        "description": "Shipment Created Event Payload",
        "bindings": {
          "kafka": {
            "bindingVersion": "0.5.0"
          }
        }
      }
    }
  },
  "operations": {
    "ExternalTransferCompleted_send_handleExternalTransferCompletedEvent": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/ExternalTransferCompleted"
      },
      "title": "ExternalTransferCompleted_send",
      "description": "External Transfer Completed Event",
      "bindings": {
        "kafka": {
          "bindingVersion": "0.5.0"
        }
      },
      "messages": [
        {
          "$ref": "#/channels/ExternalTransferCompleted/messages/ExternalTransferCompleted"
        }
      ]
    },
    "OrderFulfilled_receive_handleMessage": {
      "action": "receive",
      "channel": {
        "$ref": "#/channels/OrderFulfilled"
      },
      "title": "OrderFulfilled_receive",
      "description": "Order Fulfilled Events",
      "bindings": {
        "kafka": {
          "bindingVersion": "0.5.0"
        }
      },
      "messages": [
        {
          "$ref": "#/channels/OrderFulfilled/messages/OrderFulfilled"
        }
      ]
    },
    "ShipmentCompleted_send_handleShipmentCompletedEvent": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/ShipmentCompleted"
      },
      "title": "ShipmentCompleted_send",
      "description": "Shipment Completed Event",
      "bindings": {
        "kafka": {
          "bindingVersion": "0.5.0"
        }
      },
      "messages": [
        {
          "$ref": "#/channels/ShipmentCompleted/messages/ShipmentCompleted"
        }
      ]
    },
    "ShipmentCreated_send_handleShipmentCreatedEvent": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/ShipmentCreated"
      },
      "title": "ShipmentCreated_send",
      "description": "Shipment Created Event",
      "bindings": {
        "kafka": {
          "bindingVersion": "0.5.0"
        }
      },
      "messages": [
        {
          "$ref": "#/channels/ShipmentCreated/messages/ShipmentCreated"
        }
      ]
    }
  }
}
