{
  "asyncapi": "3.0.0",
  "info": {
    "title": "partner-order-provider-service",
    "version": "0.0.1",
    "x-generator": "springwolf"
  },
  "defaultContentType": "application/json",
  "servers": {
    "kafka-server": {
      "host": "localhost:29092",
      "protocol": "kafka"
    }
  },
  "channels": {
    "CancelOrderReceived": {
      "address": "CancelOrderReceived",
      "messages": {
        "CancelOrderReceived": {
          "$ref": "#/components/messages/CancelOrderReceived"
        }
      }
    },
    "ModifyOrderReceived": {
      "address": "ModifyOrderReceived",
      "messages": {
        "ModifyOrderReceived": {
          "$ref": "#/components/messages/ModifyOrderReceived"
        }
      }
    },
    "OrderReceived": {
      "address": "OrderReceived",
      "messages": {
        "OrderReceived": {
          "$ref": "#/components/messages/OrderReceived"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CancelOrderPayload": {
        "title": "CancelOrderPayload",
        "type": "object",
        "properties": {
          "cancelDate": {
            "title": "Cancel Date",
            "type": "string",
            "description": "The cancel date",
            "examples": [
              "2025-01-01 11:09:55"
            ]
          },
          "cancelEmployeeCode": {
            "title": "Cancel Employee Code",
            "type": "string",
            "description": "The cancel employee code",
            "examples": [
              "ee1bf88e-2137-4a17-835a-d43e7b738374"
            ]
          },
          "cancelReason": {
            "title": "Cancel Reason",
            "type": "string",
            "description": "The cancel reason",
            "examples": [
              "Customer no longer need"
            ]
          },
          "externalId": {
            "title": "External Order ID",
            "type": "string",
            "description": "The external order ID",
            "examples": [
              "ABC56865"
            ]
          }
        },
        "description": "Cancel Order Received Event Payload",
        "examples": [
          {
            "cancelDate": "2025-01-01 11:09:55",
            "cancelEmployeeCode": "ee1bf88e-2137-4a17-835a-d43e7b738374",
            "cancelReason": "Customer no longer need",
            "externalId": "ABC56865"
          }
        ],
        "required": [
          "cancelDate",
          "cancelReason",
          "externalId"
        ]
      },
      "CancelOrderReceived": {
        "title": "CancelOrderReceived",
        "type": "object",
        "properties": {
          "eventId": {
            "title": "Event ID",
            "type": "string",
            "description": "The event ID",
            "format": "uuid",
            "examples": [
              "ae94cf69-6863-4c26-ad34-99347a9a4c8a"
            ]
          },
          "eventType": {
            "title": "Event Type",
            "type": "string",
            "description": "The event type",
            "examples": [
              "CollectionReceived"
            ]
          },
          "eventVersion": {
            "title": "Event Version",
            "type": "string",
            "description": "The event version",
            "examples": [
              "1.0"
            ]
          },
          "occurredOn": {
            "title": "Occurred On",
            "type": "string",
            "description": "When the event occurred",
            "format": "date-time",
            "examples": [
              "2024-10-07T20:59:16.925110827Z"
            ]
          },
          "payload": {
            "$ref": "#/components/schemas/CancelOrderPayload"
          }
        },
        "description": "Cancel Order Received Event",
        "examples": [
          {
            "eventId": "ae94cf69-6863-4c26-ad34-99347a9a4c8a",
            "eventType": "CollectionReceived",
            "eventVersion": "1.0",
            "occurredOn": "2024-10-07T20:59:16.925110827Z",
            "payload": {
              "cancelDate": "2025-01-01 11:09:55",
              "cancelEmployeeCode": "ee1bf88e-2137-4a17-835a-d43e7b738374",
              "cancelReason": "Customer no longer need",
              "externalId": "ABC56865"
            }
          }
        ],
        "required": [
          "eventId",
          "eventType",
          "eventVersion",
          "occurredOn",
          "payload"
        ]
      },
      "Headers-1296848181": {
        "title": "Headers-1296848181",
        "type": "object",
        "properties": {
          "__TypeId__": {
            "type": "string",
            "description": "Spring Type Id Header",
            "enum": [
              "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.OrderReceived"
            ],
            "examples": [
              "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.OrderReceived"
            ]
          }
        },
        "examples": [
          {
            "__TypeId__": "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.OrderReceived"
          }
        ]
      },
      "Headers-1426470477": {
        "title": "Headers-1426470477",
        "type": "object",
        "properties": {
          "__TypeId__": {
            "type": "string",
            "description": "Spring Type Id Header",
            "enum": [
              "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.CancelOrderReceivedEvent"
            ],
            "examples": [
              "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.CancelOrderReceivedEvent"
            ]
          }
        },
        "examples": [
          {
            "__TypeId__": "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.CancelOrderReceivedEvent"
          }
        ]
      },
      "Headers-1483022323": {
        "title": "Headers-1483022323",
        "type": "object",
        "properties": {
          "__TypeId__": {
            "type": "string",
            "description": "Spring Type Id Header",
            "enum": [
              "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.ModifyOrderReceivedEvent"
            ],
            "examples": [
              "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.ModifyOrderReceivedEvent"
            ]
          }
        },
        "examples": [
          {
            "__TypeId__": "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.event.ModifyOrderReceivedEvent"
          }
        ]
      },
      "ModifyOrderReceived": {
        "title": "ModifyOrderReceived",
        "type": "object",
        "properties": {
          "eventId": {
            "title": "Event ID",
            "type": "string",
            "description": "The event ID",
            "format": "uuid",
            "examples": [
              "ae94cf69-6863-4c26-ad34-99347a9a4c8a"
            ]
          },
          "eventType": {
            "title": "Event Type",
            "type": "string",
            "description": "The event type",
            "examples": [
              "CollectionReceived"
            ]
          },
          "eventVersion": {
            "title": "Event Version",
            "type": "string",
            "description": "The event version",
            "examples": [
              "1.0"
            ]
          },
          "occurredOn": {
            "title": "Occurred On",
            "type": "string",
            "description": "When the event occurred",
            "format": "date-time",
            "examples": [
              "2024-10-07T20:59:16.925110827Z"
            ]
          },
          "payload": {
            "$ref": "#/components/schemas/com.arcone.biopro.distribution.partnerorderprovider.infrastructure.listener.dto.ModifyOrderDTO"
          }
        },
        "description": "Modify Order Received Event",
        "examples": [
          {
            "eventId": "ae94cf69-6863-4c26-ad34-99347a9a4c8a",
            "eventType": "CollectionReceived",
            "eventVersion": "1.0",
            "occurredOn": "2024-10-07T20:59:16.925110827Z",
            "payload": {
              "comments": "string",
              "deliveryType": "string",
              "desiredShippingDate": "string",
              "externalId": "string",
              "locationCode": "string",
              "modifyDate": "string",
              "modifyEmployeeCode": "string",
              "orderItems": [
                {
                  "bloodType": "string",
                  "comments": "string",
                  "productFamily": "string",
                  "quantity": 0
                }
              ],
              "productCategory": "string",
              "shipmentType": "string",
              "shippingMethod": "string",
              "willPickUp": true,
              "willPickUpPhoneNumber": "string"
            }
          }
        ],
        "required": [
          "eventId",
          "eventType",
          "eventVersion",
          "occurredOn",
          "payload"
        ]
      },
      "OrderReceived": {
        "title": "OrderReceived",
        "type": "object",
        "properties": {
          "eventId": {
            "title": "Event ID",
            "type": "string",
            "description": "The event ID",
            "format": "uuid",
            "examples": [
              "ae94cf69-6863-4c26-ad34-99347a9a4c8a"
            ]
          },
          "eventType": {
            "title": "Event Type",
            "type": "string",
            "description": "The event type",
            "examples": [
              "CollectionReceived"
            ]
          },
          "eventVersion": {
            "title": "Event Version",
            "type": "string",
            "description": "The event version",
            "examples": [
              "1.0"
            ]
          },
          "occurredOn": {
            "title": "Occurred On",
            "type": "string",
            "description": "When the event occurred",
            "format": "date-time",
            "examples": [
              "2024-10-07T20:59:16.925110827Z"
            ]
          },
          "payload": {
            "$ref": "#/components/schemas/com.arcone.biopro.distribution.partnerorderprovider.infrastructure.listener.dto.OrderDTO"
          }
        },
        "description": "Order Received Event",
        "examples": [
          {
            "eventId": "ae94cf69-6863-4c26-ad34-99347a9a4c8a",
            "eventType": "CollectionReceived",
            "eventVersion": "1.0",
            "occurredOn": "2024-10-07T20:59:16.925110827Z",
            "payload": {
              "billingCustomerCode": "string",
              "comments": "string",
              "createDate": "string",
              "createEmployeeCode": "string",
              "deliveryType": "string",
              "desiredShippingDate": "string",
              "externalId": "string",
              "locationCode": "string",
              "orderItems": [
                {
                  "bloodType": "string",
                  "comments": "string",
                  "productFamily": "string",
                  "quantity": 0
                }
              ],
              "orderStatus": "string",
              "productCategory": "string",
              "shipmentType": "string",
              "shippingCustomerCode": "string",
              "shippingMethod": "string",
              "willPickUp": true,
              "willPickUpPhoneNumber": "string"
            }
          }
        ],
        "required": [
          "eventId",
          "eventType",
          "eventVersion",
          "occurredOn",
          "payload"
        ]
      },
      "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.listener.dto.ModifyOrderDTO": {
        "title": "Payload",
        "type": "object",
        "properties": {
          "comments": {
            "type": "string"
          },
          "deliveryType": {
            "type": "string"
          },
          "desiredShippingDate": {
            "type": "string"
          },
          "externalId": {
            "type": "string"
          },
          "locationCode": {
            "type": "string"
          },
          "modifyDate": {
            "type": "string"
          },
          "modifyEmployeeCode": {
            "type": "string"
          },
          "orderItems": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/com.arcone.biopro.distribution.partnerorderprovider.infrastructure.listener.dto.OrderItemDTO"
            }
          },
          "productCategory": {
            "type": "string"
          },
          "shipmentType": {
            "type": "string"
          },
          "shippingMethod": {
            "type": "string"
          },
          "willPickUp": {
            "type": "boolean"
          },
          "willPickUpPhoneNumber": {
            "type": "string"
          }
        },
        "description": "The event payload",
        "examples": [
          {
            "comments": "string",
            "deliveryType": "string",
            "desiredShippingDate": "string",
            "externalId": "string",
            "locationCode": "string",
            "modifyDate": "string",
            "modifyEmployeeCode": "string",
            "orderItems": [
              {
                "bloodType": "string",
                "comments": "string",
                "productFamily": "string",
                "quantity": 0
              }
            ],
            "productCategory": "string",
            "shipmentType": "string",
            "shippingMethod": "string",
            "willPickUp": true,
            "willPickUpPhoneNumber": "string"
          }
        ]
      },
      "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.listener.dto.OrderDTO": {
        "title": "Payload",
        "type": "object",
        "properties": {
          "billingCustomerCode": {
            "type": "string"
          },
          "comments": {
            "type": "string"
          },
          "createDate": {
            "type": "string"
          },
          "createEmployeeCode": {
            "type": "string"
          },
          "deliveryType": {
            "type": "string"
          },
          "desiredShippingDate": {
            "type": "string"
          },
          "externalId": {
            "type": "string"
          },
          "locationCode": {
            "type": "string"
          },
          "orderItems": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/com.arcone.biopro.distribution.partnerorderprovider.infrastructure.listener.dto.OrderItemDTO"
            }
          },
          "orderStatus": {
            "type": "string"
          },
          "productCategory": {
            "type": "string"
          },
          "shipmentType": {
            "type": "string"
          },
          "shippingCustomerCode": {
            "type": "string"
          },
          "shippingMethod": {
            "type": "string"
          },
          "willPickUp": {
            "type": "boolean"
          },
          "willPickUpPhoneNumber": {
            "type": "string"
          }
        },
        "description": "The event payload",
        "examples": [
          {
            "billingCustomerCode": "string",
            "comments": "string",
            "createDate": "string",
            "createEmployeeCode": "string",
            "deliveryType": "string",
            "desiredShippingDate": "string",
            "externalId": "string",
            "locationCode": "string",
            "orderItems": [
              {
                "bloodType": "string",
                "comments": "string",
                "productFamily": "string",
                "quantity": 0
              }
            ],
            "orderStatus": "string",
            "productCategory": "string",
            "shipmentType": "string",
            "shippingCustomerCode": "string",
            "shippingMethod": "string",
            "willPickUp": true,
            "willPickUpPhoneNumber": "string"
          }
        ]
      },
      "com.arcone.biopro.distribution.partnerorderprovider.infrastructure.listener.dto.OrderItemDTO": {
        "title": "OrderItemDTO",
        "type": "object",
        "properties": {
          "bloodType": {
            "type": "string"
          },
          "comments": {
            "type": "string"
          },
          "productFamily": {
            "type": "string"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          }
        },
        "examples": [
          {
            "bloodType": "string",
            "comments": "string",
            "productFamily": "string",
            "quantity": 0
          }
        ]
      }
    },
    "messages": {
      "CancelOrderReceived": {
        "headers": {
          "$ref": "#/components/schemas/Headers-1426470477"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "$ref": "#/components/schemas/CancelOrderReceived"
          }
        },
        "name": "CancelOrderReceived",
        "title": "CancelOrderReceived",
        "description": "Cancel Order Received Event",
        "bindings": {
          "kafka": {
            "bindingVersion": "0.5.0"
          }
        }
      },
      "ModifyOrderReceived": {
        "headers": {
          "$ref": "#/components/schemas/Headers-1483022323"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "$ref": "#/components/schemas/ModifyOrderReceived"
          }
        },
        "name": "ModifyOrderReceived",
        "title": "ModifyOrderReceived",
        "description": "Modify Order Received Event",
        "bindings": {
          "kafka": {
            "bindingVersion": "0.5.0"
          }
        }
      },
      "OrderReceived": {
        "headers": {
          "$ref": "#/components/schemas/Headers-1296848181"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "$ref": "#/components/schemas/OrderReceived"
          }
        },
        "name": "OrderReceived",
        "title": "OrderReceived",
        "description": "Order Received Event",
        "bindings": {
          "kafka": {
            "bindingVersion": "0.5.0"
          }
        }
      }
    }
  },
  "operations": {
    "CancelOrderReceived_send_handleUserCancelOrderReceivedEvent": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/CancelOrderReceived"
      },
      "title": "CancelOrderReceived_send",
      "description": "Cancel Order Received Event",
      "bindings": {
        "kafka": {
          "bindingVersion": "0.5.0"
        }
      },
      "messages": [
        {
          "$ref": "#/channels/CancelOrderReceived/messages/CancelOrderReceived"
        }
      ]
    },
    "ModifyOrderReceived_send_handleModifyOrderReceivedEvent": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/ModifyOrderReceived"
      },
      "title": "ModifyOrderReceived_send",
      "description": "Modify Order Received Event",
      "bindings": {
        "kafka": {
          "bindingVersion": "0.5.0"
        }
      },
      "messages": [
        {
          "$ref": "#/channels/ModifyOrderReceived/messages/ModifyOrderReceived"
        }
      ]
    },
    "OrderReceived_send_handleUserPartnerOrderReceivedEvent": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/OrderReceived"
      },
      "title": "OrderReceived_send",
      "description": "Order Received Event",
      "bindings": {
        "kafka": {
          "bindingVersion": "0.5.0"
        }
      },
      "messages": [
        {
          "$ref": "#/channels/OrderReceived/messages/OrderReceived"
        }
      ]
    }
  }
}
